version: '3'
services:
  mariadb:
    image: bitnami/mariadb:10.3-debian-10
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_PASSWORD=magento_db_password
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - mariadb_data:/bitnami
  magento:
    image: bitnami/magento:${MAGENTO_IMAGE_VERSION}
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_USERNAME=admin
      - MAGENTO_PASSWORD=admin123
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_PASSWORD=magento_db_password
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - magento_data:${MAGENTO_VOLUME_PATH}
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    image: bitnami/elasticsearch:6-debian-10
    volumes:
      - elasticsearch_data:/bitnami/elasticsearch/data
volumes:
  elasticsearch_data:
  mariadb_data:
  magento_data:
